### PR TITLE
refactored package

### LINKED ISSUE #1: Reimplement add_edges as node visitor
Rather than parsing the newick string here
https://github.com/pylogeny/tree/blob/d5e2bca1c272cbbe36571401e7cdd20f7fcf2efb/src/pylotree/tree.py#L5
`add_edges` could be implemented as node visitor for `newick.Node.visit`:
```python
>>> import newick
>>> t = newick.loads('((a,b),c);')[0]
>>> class EdgeLabels:
...     def __init__(self):
...         self.count = 0
...     def __call__(self, node):
...         if not node.name:
...             if not node.ancestor:
...                 node.name = 'Root'
...             else:
...                 self.count += 1
...                 node.name = 'Edge{}'.format(self.count)
... 
>>> t.visit(EdgeLabels())
>>> t.newick
'((a,b)Edge1,c)Root'
```

### PR DESCRIPTION
**Pull request by xrotwang**
Since this is intended to be a micro package (?), I just turned into into a single module, saving some of the overhead that comes with packages (i.e. `__init__.py`).

I also refactored the `Tree` class to **not** store the `node_dict`. The advantage of this is that tree manipulations like renaming nodes or pruning are possible and `__getitem__` will still work as expected. This comes at the disadvantage of having to traverse the tree for each `__getitem__` call. So my proposal follows the "pre-mature optimization is the root of all evil" mantra. Do we know of any performance characteristics this code should have right now?

closes #1

### CODE REVIEW

**Comment by LinguList** [comment]
@PhyloStar, what do you think about performance? Do we need to access nodes often?

**Comment by LinguList** [comment]
@PhyloStar, what do you think about performance? Do we need to access nodes often?

**Comment by LinguList** [comment]
For me, this is very useful, and I'll probably then put my parsimony code also into a single file module. I think we can directly merge it, but I'd like @PhyloStar to also have a quick look, as you'll probably later want to add additional tree handling functions.

**Comment by xrotwang** [comment]
From what I've seen so far, `parsimony_down` could be a case, where nodes are accessed quite a bit. But then, a node `dict` could just be created and used within this function. This approach would break down, if we run `parsimony_down` multiple time on the same tree - but is this a common use case?

**Comment by LinguList** [comment]
parsimony_down is usually a lot applied to the same tree, if you have many characters, but since we only need the traversal, so we only need the post- and the pre-order, we could even do simply with those lists. So I think this should not be a problem.

**Comment by LinguList** [comment]
so I'd say we merge this now and see later, if problems turn up with performance, how to optimize them!

**Comment by PhyloStar** [comment]
I am still digesting the Tree class code. I have few questions, comments, features:

- Is the newick tree parsed into a adjacency list? https://github.com/pylogeny/bayes/blob/master/src/cybayes/commands/mcmc_gamma.pyx#L664
- We will need a tree move like NNI implemented here: https://github.com/pylogeny/bayes/blob/master/src/cybayes/commands/mcmc_gamma.pyx#L235
- We need the branch lengths for likelihood computation: https://github.com/pylogeny/bayes/blob/master/src/cybayes/commands/mcmc_gamma.pyx#L664
- The tree moves functionalities in bayes package should be dependent on the Tree package. That is the ideal situation.

**Comment by LinguList** [comment]
Branch lengths are suppored in python-newick, as far as I understand.

**Comment by PhyloStar** [comment]
> parsimony_down is usually a lot applied to the same tree, if you have many characters, but since we only need the traversal, so we only need the post- and the pre-order, we could even do simply with those lists. So I think this should not be a problem.

Yes, we can store in a list the order of the nodes in the tree. Then, apply parsimony_down or likelihood function. Whenever we manipulate the tree structure, then we update the postorder list of the nodes so that the next likelihood function computation can be done. The likelihood function calculate is here: https://github.com/pylogeny/bayes/blob/master/src/cybayes/commands/ML_scaled_cache.pyx#L68

**Comment by xrotwang** [comment]
@PhyloStar thanks for the update on what's needed! That puts things into perspective - because right now, the Tree class isn't much more than a `newick.Node` with labelled internal nodes plus
```python
{n.name: n for n in tree.walk()}
```
So, probably not worth a separate package.

**Comment by xrotwang** [comment]
@PhyloStar the link to the adjacency list code seems to be the same as for the branch lengths parsing. Could you point me to the "real thing"?

**Comment by PhyloStar** [comment]
> @PhyloStar the link to the adjacency list code seems to be the same as for the branch lengths parsing. Could you point me to the "real thing"?

We need to compute a transition probability matrix for each edge by calling this function here which computes F81 model prob. matrix for each branch.
https://github.com/pylogeny/bayes/blob/master/src/cybayes/commands/mcmc_gamma.pyx#L878

If we want to modify an edge this function is called:
https://github.com/pylogeny/bayes/blob/master/src/cybayes/commands/mcmc_gamma.pyx#L109

**Comment by LinguList** [comment]
Okay, I'll merge for now and later we can discuss updates in issues!

**Pull request merged**
